### ISSUE TITLE
Fatal error: Uncaught exception 'Exception' with message 'Module "Sections

### ISSUE THREAD

**Issue by arirah** [andrey900/SlimCMS#22]
After installed it is showing this error !! 

Fatal error: Uncaught exception 'Exception' with message 'Module "Sections" - don't loaded. Please сheck whether the module is installed and enabled' in E:\xampp\htdocs\slim\src\Modules\SModuleManager.php:272 Stack trace: #0 E:\xampp\htdocs\slim\src\Modules\SModuleManager.php(170): SlimCMS\Modules\SModuleManager->checkDependecies(Array) #1 E:\xampp\htdocs\slim\src\Modules\SModuleManager.php(113): SlimCMS\Modules\SModuleManager->loadModule('Breadcrumb', Object(stdClass), Object(stdClass)) #2 E:\xampp\htdocs\slim\src\Modules\SModuleManager.php(69): SlimCMS\Modules\SModuleManager->initModule('E:\\xampp\\htdocs...') #3 E:\xampp\htdocs\slim\app\bootstrap\app.php(67): SlimCMS\Modules\SModuleManager->loadModules('E:\\xampp\\htdocs...') #4 E:\xampp\htdocs\slim\public\index.php(2): require_once('E:\\xampp\\htdocs...') #5 {main} thrown in E:\xampp\htdocs\slim\src\Modules\SModuleManager.php on line 272

**Comment by andrey900** [comment]
You selected all modules when installed system?

**Comment by arirah** [comment]
Yes

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
